$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
    loop:false,
    nav:true,
    margin:20,
    dots:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
});
});
